package estosepone.pojo;
// Generated 12/10/2013 18:56:35 by Hibernate Tools 3.2.1.GA



/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private int idCiudad;
     private Provincia provincia;
     private String nombre;
     private int codigopostal;

    public Ciudad() {
    }

    public Ciudad(int idCiudad, Provincia provincia, String nombre, int codigopostal) {
       this.idCiudad = idCiudad;
       this.provincia = provincia;
       this.nombre = nombre;
       this.codigopostal = codigopostal;
    }
   
    public int getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCodigopostal() {
        return this.codigopostal;
    }
    
    public void setCodigopostal(int codigopostal) {
        this.codigopostal = codigopostal;
    }




}


