package estosepone.pojo;
// Generated 12/10/2013 18:56:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private int idEvento;
     private String nombre;
     private Date fecha;
     private Date horaInicio;
     private Date horaFin;
     private String descripcion;
     private String foto;

    public Evento() {
    }

	
    public Evento(int idEvento, String nombre, Date fecha, Date horaInicio, Date horaFin, String foto) {
        this.idEvento = idEvento;
        this.nombre = nombre;
        this.fecha = fecha;
        this.horaInicio = horaInicio;
        this.horaFin = horaFin;
        this.foto = foto;
    }
    public Evento(int idEvento, String nombre, Date fecha, Date horaInicio, Date horaFin, String descripcion, String foto) {
       this.idEvento = idEvento;
       this.nombre = nombre;
       this.fecha = fecha;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.descripcion = descripcion;
       this.foto = foto;
    }
   
    public int getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(int idEvento) {
        this.idEvento = idEvento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }




}


