package estosepone.pojo;
// Generated 12/10/2013 18:56:35 by Hibernate Tools 3.2.1.GA



/**
 * Preguntas generated by hbm2java
 */
public class Preguntas  implements java.io.Serializable {


     private int idPregunta;
     private int pregunta;

    public Preguntas() {
    }

    public Preguntas(int idPregunta, int pregunta) {
       this.idPregunta = idPregunta;
       this.pregunta = pregunta;
    }
   
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public int getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(int pregunta) {
        this.pregunta = pregunta;
    }




}


